const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];$('#year').textContent=new Date().getFullYear();
$('.menu').addEventListener('click',()=>{const n=document.querySelector('header nav');n.classList.toggle('show')});
let cart=[];const cartEl=$('.cart');function render(){const c=$('#count'),item=$('#cartItem'),total=$('#total'),checkout=$('#checkout');c.textContent=cart.length;if(!cart.length){item.textContent='Your cart is empty.';total.textContent='₹0';checkout.disabled=true;return}item.innerHTML=cart.map((x,i)=>`${x.name} — ₹${x.price.toLocaleString('en-IN')} <button data-r="${i}">×</button>`).join('<br>');const t=cart.reduce((a,x)=>a+x.price,0);total.textContent='₹'+t.toLocaleString('en-IN');checkout.disabled=false;$$('[data-r]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.r,1);render()})}
$$('.add').forEach(b=>b.onclick=()=>{const name=b.dataset.name,price=+b.dataset.price;if(!cart.some(x=>x.name===name))cart.push({name,price});render();cartEl.classList.add('open')});$('#cartBtn').onclick=()=>cartEl.classList.toggle('open');$('#cartClose').onclick=()=>cartEl.classList.remove('open');
$('#checkout').onclick=()=>{if(!cart.length)return;const t=cart.reduce((a,x)=>a+x.price,0);$('#summary').textContent=cart.map(x=>x.name).join(', ')+' · Total ₹'+t.toLocaleString('en-IN');$('#productField').value=cart.map(x=>x.name).join(', ');$('#amountField').value=t;$('#amountText').textContent=t.toLocaleString('en-IN');$('#modal').classList.add('open');cartEl.classList.remove('open')};$('#modalClose').onclick=()=>$('#modal').classList.remove('open');
const assistant=$('#assistant'),messages=$('#messages'),input=$('#chatinput');$('#chatbtn').onclick=()=>assistant.classList.toggle('open');$('#chatx').onclick=()=>assistant.classList.remove('open');$$('[data-open-chat]').forEach(b=>b.onclick=()=>assistant.classList.add('open'));
function answer(q){q=q.toLowerCase();if(q.includes('what')||q.includes('do you'))return'ORVAEN builds AI automation, websites, chatbots, media systems and focused digital products for businesses, creators and agencies.';if(q.includes('toolkit')||q.includes('price')||q.includes('999'))return'The Meta Recovery Toolkit is ₹999. It covers practical recovery, restriction and prevention guidance. It is educational and does not guarantee reinstatement.';if(q.includes('recover')||q.includes('ban')||q.includes('suspend'))return'The toolkit is a practical playbook for understanding recovery routes, support workflows, prevention and step-by-step guidance. Meta makes the final account decision.';if(q.includes('contact')||q.includes('mail')||q.includes('email'))return'Email orvaen+contact@proton.me or message @orvaen.ig on Instagram.';if(q.includes('website'))return'We build responsive, conversion-focused websites and landing pages.';if(q.includes('automation'))return'We map repetitive business work and connect the right tools into cleaner workflows.';if(q.includes('instagram'))return'Our Instagram is @orvaen.ig.';return'I can answer about ORVAEN, our services, the Meta Recovery Toolkit, pricing or contact details.'}
function send(q){if(!q.trim())return;const u=document.createElement('div');u.className='msg user';u.textContent=q;messages.appendChild(u);input.value='';setTimeout(()=>{const b=document.createElement('div');b.className='msg bot';b.textContent=answer(q);messages.appendChild(b);messages.scrollTop=messages.scrollHeight},180)}$('#chatform').onsubmit=e=>{e.preventDefault();send(input.value)};$$('.quick button').forEach(b=>b.onclick=()=>send(b.textContent));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#modal').classList.remove('open');cartEl.classList.remove('open');assistant.classList.remove('open')}});
